SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, C.M - A.SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA A
JOIN
(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS M
    FROM ECOLI_DATA
    GROUP BY YEAR 
) C
ON YEAR(A.DIFFERENTIATION_DATE) = C.YEAR
ORDER BY YEAR(A.DIFFERENTIATION_DATE) ASC, YEAR_DEV ASC