SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS I JOIN FISH_NAME_INFO AS N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.LENGTH = 
(
    SELECT MAX(LENGTH)
    FROM FISH_INFO
    WHERE I.FISH_TYPE = FISH_TYPE
)
ORDER BY I.ID ASC